### ISSUE TITLE
Is there a plugin for 1.8?

### ISSUE THREAD

**Issue by Garvbansal2008** [Sweattypalms/skyblock-remake#14]
Please tell if you have a plugin for 1.8 sir because in 1.17 game lags too much even server

**Comment by Sweattypalms** [comment]
There is unfortunately not a plugin for 1.8 currently. If your server is lagging, consider using frameworks like Purpur or Paper that optimize your gameplay. Due to the major differences in the versions and the API, I will not be making the plugin for 1.8; If you want to support 1.8 players, you can use plugins such as Viaversion.
